- name: deploy war file into webapps 
  copy: 
    src: /tmp/{{version}}-{{buildid}}.war
    dest: "{{tomcat_home_dir}}/webapps/vprofile.war"
    owner: "{{uname}}"
    group: "{{grp}}"
    remote_src: yes  
   
- name: stop tomcat service
  shell: nohup {{tomcat_home_dir}}/bin/startup.sh &
