- name: stop tomcat service
  shell: nohup {{tomcat_home_dir}}/bin/shutdown.sh &
    
- name: Check that war file exist
  stat:
    path: "{{tomcat_home_dir}}/webapps/vprofile.war"
  register: stat_result
      
- name: Delete the war file, if it exist already
  file:
    path: "{{tomcat_home_dir}}/webapps/vprofile.war"
    state: absent
  when: stat_result.stat.exists == True
      
- name: Check that vprofile dir exist
  stat:
    path: "{{tomcat_home_dir}}/webapps/vprofile"
  register: stat_result

- name: Delete the vprofile dir, if it exist already
  file:
    path: "{{tomcat_home_dir}}/webapps/vprofile"
    state: absent
